# Generated by Django 2.1.15 on 2021-03-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0002_auto_20210314_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='indentmaster',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
