# Generated by Django 2.1.15 on 2021-03-16 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0003_indentmaster_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indenttransactions',
            old_name='indent_no',
            new_name='indent_master',
        ),
    ]
