# Generated by Django 2.1.15 on 2021-03-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indent', '0004_auto_20210316_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indentmaster',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='indentmaster',
            name='indent_no',
        ),
        migrations.AddField(
            model_name='indentmaster',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
