# Generated by Django 2.1.15 on 2021-03-13 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent_date', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('indented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['indented_by'],
            },
        ),
        migrations.CreateModel(
            name='IndentTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indent_quantity', models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=10, null=True, verbose_name='Indented Quantity')),
                ('units', models.CharField(choices=[('Kgs', 'Kgs'), ('gms', 'Gms'), ('Nos', 'Nos'), ('Ltrs', 'Ltrs'), ('Mtrs', 'Mtrs')], max_length=5, verbose_name='Units')),
                ('required_for', models.CharField(blank=True, max_length=50, null=True, verbose_name='Required for')),
                ('approved', models.BooleanField(default=False, null=True, verbose_name='Approved?')),
                ('approved_on', models.DateTimeField(auto_now=True, verbose_name='Approved on')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indentor', to=settings.AUTH_USER_MODEL, verbose_name='Indentor')),
                ('indent_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['part'],
            },
        ),
        migrations.RemoveField(
            model_name='indent',
            name='indent_approved_by',
        ),
        migrations.RemoveField(
            model_name='indent',
            name='indented_by',
        ),
        migrations.RemoveField(
            model_name='indent',
            name='part',
        ),
        migrations.AlterField(
            model_name='partsmaster',
            name='item_name',
            field=models.CharField(blank=True, help_text='Enter Item Name', max_length=50, null=True, verbose_name='Item Name'),
        ),
        migrations.DeleteModel(
            name='Indent',
        ),
        migrations.AddField(
            model_name='indenttransactions',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.PartsMaster'),
        ),
    ]
