# Generated by Django 2.1.15 on 2021-03-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210313_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indentmaster',
            name='id',
        ),
        migrations.AddField(
            model_name='indentmaster',
            name='indent_no',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
