# Generated by Django 2.1.15 on 2021-03-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20210313_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indentmaster',
            name='indented_by',
        ),
        migrations.RemoveField(
            model_name='indenttransactions',
            name='indent',
        ),
        migrations.RemoveField(
            model_name='indenttransactions',
            name='part',
        ),
        migrations.DeleteModel(
            name='IndentMaster',
        ),
        migrations.DeleteModel(
            name='IndentTransactions',
        ),
    ]
